{
	"version": 1515240434,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/dude-sheet0.png",
		"images/tiledbackground2.png",
		"images/bg-sheet0.png",
		"images/bg-sheet1.png",
		"images/tilemap.png",
		"images/collision-sheet0.png",
		"images/tilemap2.png",
		"images/tilemap4.png",
		"images/tiles.png",
		"images/badfella-sheet0.png",
		"images/badfella-sheet1.png",
		"images/badfellaspawner-sheet0.png",
		"images/sprite-sheet0.png",
		"images/spawner2-sheet0.png",
		"images/fireting-sheet0.png",
		"images/spritefont.png",
		"images/dook-sheet0.png",
		"images/bg2-sheet0.png",
		"images/bat-sheet0.png",
		"images/slime-sheet0.png",
		"images/slime-sheet1.png",
		"images/fireball-sheet0.png",
		"images/boss-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/bgboss-sheet0.png",
		"images/sprite8-sheet0.png",
		"media/wa wa waaaa.m4a",
		"media/wa wa waaaa.ogg",
		"media/start.m4a",
		"media/start.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}